@HospitalManagementSystem_HostAddress = http://localhost:5127

### GET all patients
GET {{HospitalManagementSystem_HostAddress}}/api/patients
Accept: application/json

###

### GET patients filtered by search
GET {{HospitalManagementSystem_HostAddress}}/api/patients?search=an
Accept: application/json

###

### POST assign patient to bed
POST {{HospitalManagementSystem_HostAddress}}/api/patients/90010112345/bedassignments
Content-Type: application/json

{
  "from": "2026-05-20T14:00:00",
  "to": "2026-05-30T10:00:00",
  "bedType": "Standard",
  "ward": "Kardiologia"
}

###

### POST assign patient to bed
POST {{HospitalManagementSystem_HostAddress}}/api/patients/85050567890/bedassignments
Content-Type: application/json

{
  "from": "2026-06-01T09:00:00",
  "bedType": "Intensywna terapia",
  "ward": "Chirurgia"
}

###
